### ISSUE TITLE
new unrecognized game

### ISSUE THREAD

**Issue by alucard73** [screemerpl/cbleemsync#14]
Hello
I announce you that there is a major bug, but which comes especially from the bootmenu .02 beta
I explain (sorry for my english), before I used bleemsync 0.4.1, then Bootmenu, but now, since the bootmenu pass, as soon as we added a game on the usb, no game was launched, the solution was to hand lolhack of bleemsync 0.4.1 for which to recreate a database and then put back the bootmenu lolhack so that my games with those add up works again. This bug is also present in your program that I like a lot, once the lolhack of your program delivered, so I must redo a re-scan and everything works, but as soon as I add a game I must redo what I have said.
Another small problem that would be nice to integrate into autobleem is as for cue + bin the ability to put several eboot (ex: alone in the dark eboot1.pbp and eboot2.pbp separately to change the CD by simply pressing Eject at instead of creating a single multidisc eboot and having to go through the hide and change disc menu)

Thanks for reading me

**Comment by screemerpl** [comment]
I am not sure if PCSX-Rearmed (that PlayStation Classic uses) can support multiple PBP files that you mentioned.  I need to have a look on this problem... maybe I will find it out :) ... thank you for your report. I do not understand the first part,  the description of the issue is not very clear ... lolhack folder in autobleem is totally different and if you replace it from bleemsync ... this will not work at all... can you make a screenshot or video of the problem and post the link.... When you add a game folder, AutoBleem will scan it on boot time, but games that are scanned and have valid data are just skipped (so scan takes no time on them) - AutoBleem should show you a message to press "X" and then scan takes place. Adding/removing games DOES NOT force to change any other file on the USB.

**Comment by alucard73** [comment]
Sorry I do not know how to explain and I can not make video because of poor image quality

In short, I wanted to suggest other options that could be grafted into your program for as complete as possible, but nothing requires you to do so.

1. way to link the same memory card between multiple games? Maybe something like putting a config to the game. i do not know what i mean if i do not know what i want to do. or even games with shared memory card like Arc the Lad.

2. I happened to forget to create a GameData folder, it would be nice if you forgot to do that your program create the folder and it copies the files we have in GameData

**Comment by alucard73** [comment]
i may not be careful though i am sure the gamedata create it did not move the games in, i would try again.

In any case thank you for reading me
