### ISSUE TITLE
slow retroarch

### ISSUE THREAD

**Issue by alimadhi** [screemerpl/cbleemsync#189]
when running SNES, Mega CD, Sega Saturn and dreamcast games running slow 
i have PAl PS Classic

**Comment by screemerpl** [comment]
The reason is simple ... PSClassic CPU is too slow itself to run some complex games from other platforms like mentioned by you Dreamcast (some games run ok, but many of them will be very slow ) and Saturn (the speed is mostly terrible) games. The attached cores are distributed as they are and we do not have any solution for hardware performance.
