### ISSUE TITLE
Setup stable toolchain that can build AutoBleem and pcsx_rearmed 

### ISSUE THREAD

**Issue by screemerpl** [screemerpl/cbleemsync#64]

**Comment by screemerpl** [comment]
I think we can close this

**Comment by mGGk-fr** [comment]
As we have a compatible build server for PCSX and a full toolchain for autobleem ui, we can put this aside.

**Comment by screemerpl** [comment]
closing this as cross compile toolchain already created

**Comment by michaelshmitty** [comment]
Hi @screemerpl 

I was hoping you could point me in the right direction. I'm not entirely new to cross compiling but this always gives me trouble. I think I understand the problem but I don't know how to solve it.
I'm trying to compile AutoBleem on Debian 9. I have the arm-linux-gnueabihf toolchain installed and everything builds up until the point that it needs to be linked with SDL:

`
[ 95%] Building CXX object CMakeFiles/autobleem-gui.dir/src/code/launcher/ps_zoom_btn.cpp.o
[ 97%] Building CXX object CMakeFiles/autobleem-gui.dir/src/code/launcher/ps_meta.cpp.o
[100%] Linking CXX executable autobleem-gui
/usr/lib/gcc-cross/arm-linux-gnueabihf/6/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lSDL2
/usr/lib/gcc-cross/arm-linux-gnueabihf/6/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lSDL2_image
/usr/lib/gcc-cross/arm-linux-gnueabihf/6/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lSDL2_mixer
/usr/lib/gcc-cross/arm-linux-gnueabihf/6/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lSDL2_ttf
collect2: error: ld returned 1 exit status
`
I take it that the linker cannot find the SDL libs for the arm-linux-gnueabihf target, which makes sense because I don't have those on this system. I only have the libs for x86_64.
So how do you solve this when cross compiling? Do I build SDL2 from source with the arm-linux-gnueabihf toolchain or is there another way to do this?

Not entirely AutoBleem related, but I thought I'd try to ask you through this remotely related issue. Many thanks in advance and thanks for AutoBleem!

--m

**Comment by ChocoNutDancer** [comment]
I know that I did not have to build SDL2 from source.  I was new to Cmake, new to cross compiling, and new to Clion, and I had a terrible time trying to figure out how to get everything to cross compile and link and also to compile and link and run on a Linux development system.  I my case I made a VirtualBox VM running Ubuntu on a PC to do the development work.
I've forgotten the details of what I had to do to get things working but if there is something in the settings I can copy/paste or look up let me know.

**Comment by michaelshmitty** [comment]
Thanks for the reply @ChocoNutDancer 

I'm running macOS and I also set up a Linux Debian VM to do the cross compiling on because it seems easier to get a toolchain up and running.
And this works, I can cross compile a simple hello world program, copy the binary over to the PS classic and it executes fine.
It's when I start using external libs like SDL that the link step fails. This puzzles me because the SDL lib is already available on the PS classic to link with at runtime, so why does the link step during cross compiling need to have the binary lib available to complete the linking process? Or am I misunderstanding how this works?

I was hoping someone could shed a light on how the build server for Autobleem is set up to cross compile Autobleem.
I'm also watching this hoping to get more insights into cross compilation: https://www.youtube.com/watch?v=Pbt330zuNPc

**Comment by michaelshmitty** [comment]
> As we have a compatible build server for PCSX and a full toolchain for autobleem ui, we can put this aside.

@mGGk-fr do you happen to have any docs or (partial) on how this build server was set up? I would love to cross compile programs for the PS classic but I'm a bit stuck at cross compiling code depending on external libs (like SDL2). Thanks in advance!

**Comment by michaelshmitty** [comment]
@ChocoNutDancer I just found this: https://github.com/autobleem/PSC-CrossCompile-Toolchain
That's probably what I was looking for.

**Comment by ChocoNutDancer** [comment]
I was going to post that link.  But it looked like you were already using it in your command.  Were you able to get it working?
 - Axanar
